Fix admin-command, central echo for admin

diff --git a/bin/jboss7 b/bin/jboss7
--- a/bin/jboss7
+++ b/bin/jboss7
@@ -106,11 +106,12 @@ export LAUNCH_JBOSS_IN_BACKGROUND=true
 
 admin() {
   if [ "x$OPENSHIFT_HOMEDIR" = "x" ]; then
-    "$JBOSS_HOME/bin/jboss-cli.sh --connect --controller=${BIND_ADDRSS-localhost}:$JBOSS_ADMIN_PORT" $1 $2 $3
+    echo "$JBOSS_HOME/bin/jboss-cli.sh --connect --controller=${BIND_ADDRSS-localhost}:$JBOSS_ADMIN_PORT" $@
+    $JBOSS_HOME/bin/jboss-cli.sh --connect --controller=${BIND_ADDRSS-localhost}:$JBOSS_ADMIN_PORT $@
   else
     thisdir=${PWD}
     cd $JBOSS_HOME/bin/
-    jboss-cli.sh --connect --controller="${OPENSHIFT_WILDFLY_IP}:${OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT}" $1 $2 $3
+    jboss-cli.sh --connect --controller="${OPENSHIFT_WILDFLY_IP}:${OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT}" $@
     cd $thisdir
   fi
 }
@@ -189,9 +190,8 @@ configure() {
 	ext=`echo $file | sed  's/.*\.//'`
 	case "$ext" in
 	  conf|cli)
-		echo admin --file=$file
 		admin --file=$file || {
-			echo "[ERROR]: failed executing $admin --file=$file" ; exit 1
+			echo "[ERROR]: failed executing jboss-cli.sh --file=$file" ; exit 1
 		}
   	  ;;
   	  sh)
@@ -325,7 +325,7 @@ case "$action" in
         echo "$displayName not running"
     else
         echo -n "Shutting down $displayName "
-		$admin -c "shutdown" > /dev/null &
+		admin -c "shutdown" > /dev/null &
         cnt=$STOP_TIMEOUT
         while [ $cnt -gt 0 ] && is_running
         do
@@ -412,20 +412,16 @@ case "$action" in
     tail -f $out
   ;;
   deploy)
-	echo $admin \"deploy --force $deployment\"
 	admin "deploy --force $deployment"
   ;;
   undeploy)
 	name=`basename $deployment`
-	echo $admin -c "undeploy $name"
 	admin -c "undeploy $name"
   ;;
   admin)
-	echo $admin
 	admin
   ;;
   deployments)
-	echo $admin -c "ls deployment"
 	admin -c "ls deployment"
   ;;
   tear-down)
@@ -444,7 +440,7 @@ case "$action" in
     if [ -z "$deployment" ]; then
 		echo "usage: $0 $1 file.extension" 1>&2
 		echo "  where extension is in:" 1>&2
-		echo "    conf - file with commands for $admin" 1>&2
+		echo "    conf - file with commands for jboss-cli" 1>&2
 		echo "    cli - same as conf" 1>&2
 		echo "    sh   - file with shell commands. JBOSS_HOME is exported." 1>&2
 		echo "    module - Zip-file to be unpacked in $moduleDir" 1>&2
